import React from "react";
import Head from "next/head";
import data from "@/data/home.json";
import ClientLayout from "@/layouts/clientLayout";
import Card from "@/components/card";
import { useRouter } from "next/router";
import { BsThreeDotsVertical, BsThreeDots } from "react-icons/bs";


const Random = () => {
  
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Random</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <ClientLayout
        space={space.space}
        spaceDetail={space.spaceDetail}
        bgColor={"#FFFFFF"}
      >
        <div className="text-2xl px-8 lg:px-2 py-2 lg:py-0">
          By the way, <span className="text-gray-600">John</span>
        </div>
          <div className="flex mb-20 justify-center xl:justify-start flex-wrap">
            {data.map((value, key) => (
              <div
                className="mx-0 md:mx-4 lg:mx-1 mb-2 relative"
                key={key}
              >
                <div
                  className="md:mx-6 lg:mx-0 my-6 mt-6 flex justify-end relative"
                  key={key}
                >
                  <button className="hidden md:block text-2xl absolute right-3 top-5 w-4 text-[#FFD233]">
                    <BsThreeDotsVertical size={20} />
                  </button>
                  <span
                  className="w-40 h-40 md:w-60 md:h-60 lg:w-44 lg:h-48 top-16 right-2 lg:right-6 absolute cursor-pointer"
                    onClick={() => {
                      router.push("/affirmations/random/" + value.id);
                    }}
                  >
                  </span>
                  <Card
                      source={value.source}
                      message={value.message}
                      isLiked={value.liked}
                      type="small"
                    />
                  <button
                    className="block md:hidden text-2xl absolute right-6 top-60 md:top-80 w-4 text-[#FFD233]"
                    style={{ marginTop: 7 }}
                  >
                    <BsThreeDots size={20} />
                  </button>
                </div>
              </div>
            ))}
          </div>
      </ClientLayout>
    </>
  );
};

const space = {
  space: "Random Space",
  spaceDetail:
    "Like trajectories, inspiration isn't linear.Use this space to discover your affirmation in an alternative way.",
};

export default Random;
