import AuthLayout from "@/layouts/authLayout";
import Head from "next/head";
import Image from "next/image";
import logo from "@/assets/imgs/Vector.png";
import React from "react";
import { MdMarkEmailUnread } from "react-icons/md";
import Link from "next/link";

const Checkemail = () => {
  return (
    <>
      <Head>
        <title>Check Email</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <AuthLayout>
        <div className="mt-4 max-w-xs h-auto overflow-hidden bg-white rounded-2xl">
          <div className="px-14 py-10 h-full w-full  h-auto">
            <div className="flex items-center justify-center mb-3">
              <Image src={logo} alt="logo" />
            </div>
            <div className="flex items-center justify-center mb-3">
              <p className="text-xl font-bold">Check your Email.</p>
            </div>
            <div className="flex items-center justify-center mb-16">
              <p className="text-xs  text-gray-400 font-bold">
                Continue your voyage.
              </p>
            </div>
            <div className="flex items-center justify-center mb-6">
              <MdMarkEmailUnread size={75} />
            </div>
            <div className="flex mb-4">
              <p className="text-xs text-gray-600 text-center font-bold font-sans">
                If the email address you provided is registered to <b>ASTR</b>,
                you will receive an email.
              </p>
            </div>
            <div className="flex items-center justify-center mb-16">
              <p className="text-xs text-gray-600 text-center font-bold">
                This email will contain a link that will sign you in to your
                space.
              </p>
            </div>
            <div className="flex items-center justify-center mb-6">
              <Link
                href="/"
                className="text-base text-green-600 text-center font-bold"
              >
                I didn’t receive an email
              </Link>
            </div>
          </div>
        </div>
      </AuthLayout>
    </>
  );
};

export default Checkemail;
