import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "@/assets/imgs/Vector.png";
import AuthLayout from "@/layouts/authLayout";
import { LoginForm, SignupForm } from "@/components/forms/auth";

const Auth = () => {
  const [activeTab, setActiveTab] = React.useState("signin");

  return (
    <>
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <AuthLayout>
        <div className="mt-4 max-w-sm h-auto overflow-hidden bg-white rounded-2xl">
          <div className="px-5 py-10 h-full w-full h-auto">
            <div className="flex items-center justify-center mb-3">
              <Image src={logo} alt="logo" />
            </div>
            <div className="flex items-center justify-center mb-8">
              <p className="text-xl font-bold">Welcome to your space.</p>
            </div>
            <div className="flex items-center justify-center mb-8">
              <div className="flex justify-content">
                <button
                  className={`${
                    activeTab === "signin"
                      ? "border-b-2 border-yellow-400 "
                      : "text-gray-400"
                  } bg-white hover:bg-gray-100 text-gray-800 font-medium py-2 px-4`}
                  onClick={() => setActiveTab("signin")}
                >
                  Sign In
                </button>
                <button
                  className={`${
                    activeTab === "signup"
                      ? "border-b-2 border-yellow-400 "
                      : "text-gray-400"
                  } bg-white hover:bg-gray-100 text-gray-800 font-medium py-2 px-4`}
                  onClick={() => setActiveTab("signup")}
                >
                  Sign Up
                </button>
              </div>
            </div>
            <div>{activeTab === "signin" ? (<LoginForm />) : (<SignupForm />)}</div>
          </div>
        </div>
      </AuthLayout>
    </>
  );
};

export default Auth;
