import AddNewLayout from "@/layouts/addNewLayout";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import Image from "next/image";
import publicImg from "@/assets/imgs/public.svg";
import userSelection from "@/assets/imgs/publicIcon.svg"
import { useRouter } from "next/router";
import user from "@/data/user.json";
import { RxCross2, RxTriangleDown } from "react-icons/rx";
import { FaRegWindowMinimize } from "react-icons/fa";

const AddNewModal = () => {
  const [showModal, setShowModal] = React.useState(false);

  return (
    <>
      <button
        className="flex w-18 h-6 px-2 my-2 pt-0.5 border border-3 border-black m-0.5 rounded-2xl"
        onClick={() => setShowModal(true)}
      >
        <span className="text-sm text-[#373F51]">Public</span>
        <RxTriangleDown size={20} />
      </button>
 
      <div 
        className={`${
          showModal ? "translate-y-0 ease-out" : "translate-y-full ease-in"
        } fixed inset-0 flex justify-center items-end  left-0 z-50 w-full h-full overflow-x-auto transition duration-300 transform`}
      >
            <div className="bg-white lg:rounded-t-3xl h-full w-full shadow-lg overflow-hidden">
                <div className="flex justify-center px-4 py-4">
                  <button className="p-1" onClick={() => setShowModal(false)}>
                    <span className="text-black h-6 w-6 text-2xl block outline-none focus:outline-none">
                      <FaRegWindowMinimize color="#373F51" />
                    </span>
                  </button>
                </div>
                <div className="px-6 py-4">
                  <div className="flex flex-col align-center">
                    <div className="text-lg mb-4 text-center mx-16 lg:mx-0 font-bold">
                      Affirmation Visability
                    </div>
                    <div className="flex items-center justify-center">
                        <div className="w-26 h-20 relative">
                          <div className="text-dark mr-2 py-5">
                            <div className="h-12 w-12 rounded-xl bg-yellow-400 flex items-center justify-center">
                              <Image src={publicImg} width={25} alt="" />
                            </div>
                            <div className="absolute left-9 bottom-2">
                              <Image src={userSelection} width={18} alt="user selection" />
                            </div>
                          </div>
                      </div>
                      <div className="my-2 border-t-2 border-b border-solid border-slate-200">
                        <p className="text-large pt-2 pb-1 font-bold">Public</p>
                        <li className="text-xs pl-1 italic text-gray-600">
                          Will be visibile to everyone on the platform
                        </li> 
                      </div>
                    </div>
                    <div className="border-b border-solid border-slate-200 mb-4">
                      {" "}
                      <p className="text-sm my-4 text-center pt-2 pb-2 text-black">
                        More options coming soon
                      </p>
                    </div>
                </div>
              </div>
            </div>
          </div>
    </>
  );
};

const Addnew = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Add new</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <AddNewLayout>
        <div className="container py-4">
          <div className="grid grid-cols-2 xl:mx-44 mx-2">
            <div className="flex justify-start">
              <button className="text-white">
                <RxCross2 size={22} onClick={() => router.back()} />
              </button>
            </div>
            <div className="flex justify-end">
              <div className="flex bg-white w-56 h-10 px-2 rounded-md gap-2">
                <AddNewModal />
                <button className="w-18 h-6 px-2 my-2 border border-3 border-black bg-[#373F51] text-white text-sm rounded-2xl">
                  Submit
                </button>
                <div className="h-9 mt-0.5 w-px bg-[#C7C2C2]"></div>
                <Link href="/account">
                  <div
                    className={`bg-gradient-to-r text-white from-[#2CB673] to-[#0AD3FF] px-2 py-1 mt-1 rounded-full`}
                  >
                    {user.initials}
                  </div>
                </Link>
              </div>
            </div>
          </div>
          <div className="grid place-items-center gap-4 my-20 mx-2">
            <input
              type="text"
              className="bg-transparent text-center text-xl text-white placeholder-white italic border-white border-2 xl:border-4 w-full xl:w-1/2 h-14 rounded-lg"
              placeholder="Sourced from (Optional)"
            />
            <textarea
              placeholder={`I am...\n(Affirmation in first person)`}
              className="bg-transparent text-center py-24 text-2xl xl:text-4xl text-white italic border-white border-2 xl:border-4 w-full xl:w-1/2 h-80 rounded-lg focus:border-yellow-500 focus:ring focus:ring-yellow-200 focus:ring-opacity-50"
              rows={4}
              style={{
                fontWeight: "bold",
              }}
            ></textarea>

            <style jsx>{`
              ::placeholder {
                color: rgba(255, 255, 255, 0.7);
                font-weight: bold;
              }
              ::-webkit-input-placeholder {
                color: rgba(255, 255, 255, 0.7);
                font-weight: normal;
              }
            `}</style>
          </div>
        </div>
      </AddNewLayout>
    </>
  );
};

export default Addnew;
