import React from "react";
import Head from "next/head";
import data from "@/data/home.json";
import ClientLayout from "@/layouts/clientLayout";
import Card from "@/components/card";


const Likes : React.FC = () => {
  return (
    <>
      <Head>
        <title>Likes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientLayout space={space.space} spaceDetail={space.spaceDetail}>
          <div className="text-2xl ml-auto">
            Your likes, <span className="text-gray-600">John</span>
          </div>
          <div className="flex justify-center flex-wrap">
            {data.map((value, key) => (
                value.liked ?
              <div className="m-2 mt-12" key={key}>
                <Card source={value.source} message={value.message} isLiked={value.liked} type='small' />
              </div> :
              <></>
            ))}
          </div>
        </ClientLayout> 
    </>
  );
};

const space = {
  space: "Liked Space",
  spaceDetail:
    "Find and store your favourite affirmations across our platform, and build out your liked space.",
};

export default Likes;
