import Head from "next/head";
import ClientLayout from "@/layouts/clientLayout";
import { AiOutlineFund } from "react-icons/ai";
import { BiHelpCircle } from "react-icons/bi";
import { MdOutlineFeedback } from "react-icons/md";
import Badge from "@/components/badge";
import Link from "next/link";
import user from '@/data/user.json'

const Account = () => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        
        <ClientLayout space={space.space} spaceDetail={space.spaceDetail}>
          <div className="text-2xl ml-auto lg:ml-20">
            Here's your account, <span className="text-gray-600">John</span>
          </div>
          <div className="px-0 py-10 md:px-24 lg:px-36 xl:px-60 2xl:px-96">
            <div className="mt-8">
              <div className="max-w-sm h-80 overflow-hidden shadow-lg bg-gradient-to-r from-rose-100 to-teal-100 rounded-3xl">
                <div className="h-80">
                  <div className="px-3 py-3 h-full w-full flex items-center justify-center">
                    <div className="text-black text-center font-semibold">
                      <span className="bg-gradient-to-r from-[#2CB673] to-[#0AD3FF] px-4 py-3 rounded-full text-2xl text-white">
                        {user.initials}
                      </span>
                      <div className="mt-10 flex gap-16">
                        <label className="text-sm">First Name</label>
                        <label className="text-sm">Last Name</label>
                      </div>
                      <div className="mt-2 flex gap-2">
                        <input
                          type="text"
                          value={user.firstName}
                          onChange={()=>alert("Please handle the onChange event.")}
                          className="w-32 h-8 rounded-md p-1"
                        />
                        <input
                          type="text"
                          value={user.lastName}
                          onChange={()=>alert("Please handle the onChange event.")}
                          className="w-32 h-8 rounded-md p-1"
                        />
                      </div>
                      <div className="mt-8">
                        <p className="text-base font-bold">Role(s)</p>
                        <p className="text-sm mt-1">• User</p>
                      </div>
                      <button className="mt-4 text-white bg-[#0AD3FF] p-2 w-32 rounded-md">
                        Update Profile
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-12">
                <p className="text-md font-bold">STATS</p>
                <div className="max-w-sm mt-2 overflow-hidden shadow-lg bg-gradient-to-r from-rose-100 to-teal-100 rounded-3xl">
                  <div className="h-20 mb-2">
                    <div className="grid grid-cols-2 gap-1 justify-evenly">
                      <div className="w-26 h-12">
                        <p className="text-dark text-center mt-2">
                          COLLECTIONS
                        </p>
                      </div>
                      <div className="w-26 h-12">
                        <p className="text-dark text-center mt-2">
                          AFFIRMATIONS
                        </p>
                      </div>
                      <div className="w-26 h-12">
                        <p className="text-center font-bold text-xl">1</p>
                      </div>
                      <div className="w-26 h-12">
                        <p className="text-center font-bold text-xl">2</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-12">
                <p className="text-md font-bold">SUPPORT US</p>
                <Badge icon={AiOutlineFund} value="Share a Space to Remember" />
              </div>
              <div className="mt-12">
                <p className="text-md font-bold">HELP</p>
                <div className="mb-4">
                  <Badge icon={MdOutlineFeedback} value="Give us Feedback" />
                </div>
                <div className="mb-4">
                  <Badge icon={BiHelpCircle} value="Help" />
                </div>
              </div>
              <div className="mt-16 flex items-center justify-center">
                <Link href="/" className="text-[#2CB673]">Sign Out</Link>
              </div>
            </div>
          </div>
        </ClientLayout>
      </div>
    </>
  );
};

const space = {
  space: "Account Space",
  spaceDetail:
    "Get the latest additions of our ever-growing affirmation collection and like your favourite to shape your space.",
};

export default Account;
